"""
llama.cpp integration for ContextLens.

Generates command-line flags and config files for llama.cpp to use
compressed KV cache.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from contextlens.profiles import ModelProfile


def generate_flags(profile: ModelProfile, reuse_cache: int = 256) -> str:
    """Generate llama.cpp flags for KV cache quantization.

    Args:
        profile: Model profile with architecture information
        reuse_cache: Cache reuse size (default 256)

    Returns:
        String of flags to append to llama.cpp command
    """
    flags = "--cache-type-k q3_K --cache-type-v q3_K"
    
    if reuse_cache > 0:
        flags += f" --cache-reuse {reuse_cache}"
    
    return flags


def write_config_file(
    profile: ModelProfile,
    output_path: str,
    reuse_cache: int = 256,
) -> None:
    """Write a .conf file loadable via llama.cpp --config flag.

    Args:
        profile: Model profile with architecture information
        output_path: Path to write the config file
        reuse_cache: Cache reuse size (default 256)
    """
    flags = generate_flags(profile, reuse_cache)

    config_content = f"""# ContextLens configuration for {profile.model_id}
# Generated by contextlens integrate llamacpp

# KV cache quantization (TurboQuant 3-bit)
{flags}

# Model architecture (for reference)
# Layers: {profile.num_layers}
# KV Heads: {profile.num_kv_heads}
# Head Dim: {profile.head_dim}
# Dtype: {profile.dtype}
# KV Cache per 1k tokens: {profile.kv_cache_gb_per_1k_tokens:.2f} GB
"""

    output = Path(output_path).expanduser()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(config_content)


def generate_llama_cpp_python_hook(profile: ModelProfile) -> str:
    """Generate Python hook code for llama-cpp-python integration.

    This creates a snippet that can be injected into a llama-cpp-python
    script to intercept KV tensors and apply TurboQuant compression.

    Args:
        profile: Model profile

    Returns:
        Python code string for the hook
    """
    hook_code = f'''"""
ContextLens hook for llama-cpp-python
Model: {profile.model_id}
Architecture: {profile.num_layers} layers, {profile.num_kv_heads} KV heads
"""

from contextlens.compressor import TurboQuantCompressor

_compressor = TurboQuantCompressor(bits=3)


def compress_kv_cache(k_tensor, v_tensor, layer_idx):
    """Compress KV cache using TurboQuant.
    
    Args:
        k_tensor: Key tensor [batch, heads, seq_len, head_dim]
        v_tensor: Value tensor [batch, heads, seq_len, head_dim]
        layer_idx: Layer index for seeding
        
    Returns:
        Tuple of (compressed_k, compressed_v)
    """
    ck = _compressor.compress_k_cache(k_tensor, layer_idx)
    cv = _compressor.compress_v_cache(v_tensor, layer_idx)
    return ck, cv


def decompress_kv_cache(ck, cv, query):
    """Decompress KV cache for attention computation.
    
    Args:
        ck: Compressed K-cache
        cv: Compressed V-cache
        query: Query tensor for attention
        
    Returns:
        Tuple of (decompressed_k, decompressed_v)
    """
    return _compressor.decompress_for_attention(ck, cv, query)


# Example usage with llama-cpp-python:
# from llama_cpp import Llama
# llm = Llama(model_path="model.gguf", n_ctx=4096)
# 
# The compression would be applied during the attention forward pass
# by intercepting the KV cache tensors.
'''
    return hook_code


def get_llama_cpp_version() -> Optional[str]:
    """Get the installed llama-cpp-python version.

    Returns:
        Version string or None if not installed
    """
    try:
        import llama_cpp
        return getattr(llama_cpp, "__version__", "unknown")
    except ImportError:
        return None


def check_llama_cpp_installed() -> bool:
    """Check if llama-cpp-python is installed.

    Returns:
        True if installed, False otherwise
    """
    try:
        import llama_cpp
        return True
    except ImportError:
        return False
